### ISSUE TITLE
Error JQuery

### ISSUE THREAD

**Issue by kresnasatya** [opoloo/jquery_upload_preview#14]
Dear team, I find out the error that tell success_callback is not function. 
![image](https://cloud.githubusercontent.com/assets/11099186/23093575/5ad92d66-f622-11e6-85f1-ee16e0730c37.png)

I test from using jQuery 2 to 3 it shows those result. But, so far the plugin is work properly. This is just information to you. I hope this plugin still develop. Thanks

**Comment by bonucci** [comment]
Any feedback regarding about this error? I have also this error.

**Comment by MyXoToD** [comment]
@satyakresna @bonucci would you mind sending me your code including the callback function AND the plugin init?

EDIT: I just merge a pull request fixing an issue regarding the callback function. Tested & worked.
