### ISSUE TITLE
validate image extension on upload

### ISSUE THREAD

**Issue by leandroruel** [opoloo/jquery_upload_preview#16]
it already does it, but i want handle the file type. i mean, if an image is gif, it is not valid, would be great a function "onUpload" or "onChange". i tried it using jquery events but the plugin always show the preview when i try not do it.

**Comment by MyXoToD** [comment]
This could be useful indeed. Since I don't have the time right now to implement this I would recommend to add it yourself or update the not minified version of the script inside of your project. Be careful though you might undo any changes if you update in the future.
