### ISSUE TITLE
Clear preview

### ISSUE THREAD

**Issue by GCalmels** [opoloo/jquery_upload_preview#18]
Hey, thanks for your work,
I guess it could be great if this lib can have an option to clear a preview no?
Like a close icon if a preview is present

**Comment by MyXoToD** [comment]
Sure, this would be a good idea. Currently there is no other way than to clear the background property of your preview element by hand (not very much effort). If you think it would be necessary to have function do that within the plugin then go ahead and implement it :)

For now I'd suggest removing the background image from the background element. Just add a simple click event listener that clears the background. If I should work on this plugin again I'll make sure to include this function.
