### ISSUE TITLE
Как добавить крестик delete?

### ISSUE THREAD

**Issue by moireceptik** [opoloo/jquery_upload_preview#21]
Подскажите пож-та - а как осуществить удаление миниатюры? Мне нужно чтобы после отображения миниатюры появился на фото крестик, при нажатии на который - миниатюра должна удалиться (исчезнуть) из блока в котором она отображается.

**Comment by MyXoToD** [comment]
I don't speak russian. If you need any help I would need an english translation of that.

**Comment by moireceptik** [comment]
Прошу доработать плагин: 1. После загрузки изображения надпись "Change File" исчезает, картинка загружается и появляется крестик (удалить). 2. При нажатии на крестик (удалить) - фото удаляется и опять появляется надпись "Change File".

Please modify the plugin: 1. After loading the image, the inscription "Change File" disappears, the picture is loaded and a cross (delete) appears. 2. When you click on the cross (delete) - the photo is deleted and the inscription "Change File"appears again.

**Comment by MyXoToD** [comment]
I'm sorry to tell you, that this won't be updated anymore. It's open source so people can add what they need to it.
