### ISSUE TITLE
the image preview functionality does seem to work with my firefox 

### ISSUE THREAD

**Issue by gogo52cn** [opoloo/jquery_upload_preview#3]
the image preview functionality does seem to work with my firefox.

It works with chrome though.

my version of firefox is v42.0

**Comment by orijmm** [comment]
Hi! 

You need "event" to be a parameter to the handlers.

in jquery.uploadPreview.js

line 18: $(settings.input_field).change(function() {
change for
$(settings.input_field).change(function(event) {

**Comment by MyXoToD** [comment]
This has been fixed, see Issue #6.
