### ISSUE TITLE
Please update assets in website

### ISSUE THREAD

**Issue by relu-xz** [opoloo/jquery_upload_preview#6]
The demo is not working on Firefox:

```
ReferenceError: event is not defined                uploadPreview.js:19:17
```

[http://opoloo.github.io/jquery_upload_preview/](http://opoloo.github.io/jquery_upload_preview/)

Thanks.

**Comment by AtlasNCz** [comment]
Hi!

You need "event" to be a parameter to the handlers.

in jquery.uploadPreview.js

line 18: $(settings.input_field).change(function() {
change for
$(settings.input_field).change(function(event) {

Or in jquery.uploadPreview.js

line 19: var files = event.target.files;
change for
var files = this.files;

Both work

**Comment by MyXoToD** [comment]
I noticed that this bug has been fixed on September 29th, 2015. Closed.

**Comment by relu-xz** [comment]
@MyXoToD That was I mean, the website was using an old version of the plugin. Thanks.
